jwt:
  secret: supermegasecretcode

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/berboapp
    password: ${PASSWORD}
    username: root
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/berboapp
    user: root
    password: ${PASSWORD}
    schemas: berboapp
    locations: classpath:db/migration/mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
  sql:
      init:
        mode: never
        continue-on-error: false